name: Esteira de entrega
on: push

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: Exibir mensagem inicial
        run: echo "Hello world"

      - name: Setup java
        uses: actions/checkout@v6
      - uses: actions/setup-java@v5
        with:
          distribution: 'corretto'
          java-version: '17'
          cache: 'maven'
          cache-dependency-path: 'cardapio-backend/pom.xml'

      - name: Build e testes backend
        run: mvn -B package --file cardapio-backend/pom.xml

      - name: Rodar Checkstyle
        run: mvn checkstyle:check --file cardapio-backend/pom.xml || true